language: node_js
node_js:
- '0.12'
- '0.11'
- iojs-v1
- iojs-v2
script: npm test
before_script:
- npm install
after_success:
- ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    secure: FuRaQjnEpteY819AhNyUI1y41jeAxVribPXqbMexgusX52qqAZq2V5OHa7Q+wJon7sFe3U1n4oJeBz8Qc/axM7fyUNqPt+0Nsp6mExKo/Q8xx60HpdwFzp+E5tb/ceCfjKDAWj3HgmTHrEWLKZ1vrUDObjgdVPkftegGbdBTi3CqCFzBywYe0INPsUA9KZjFRsHfsJRgri9aw8gCYEj+qBYXmL4LdTVWH9q0hX6ZcksDaKSUaSGR3ok12yZQRG4+BOsTIU27NRQxEdF7k4cNW0bfmr5PRvbG0W1sgvWiRMOOnUXAnHk7AsjYtpARZDIrCGHBarNM/f37e8dwK4XuUsAgLO4x5sT6VdKXKil4FOZSWYaNvbKnnnOKnNy+78IRQGjg7pTub5PBNeCtBggG8A1Oa+NH5L3D7OcJrS1FpsY9jmyyM9usE76iKO3lvrY5e4xZ5+gXGLifXaN6VegLQx4coGBLx3PH0qiFfGDPh0CR9Qi2Q5qQ8UU7Luorx/ysI2esEVLY1s8ITwiz6UPTJWP5N//ptWCH0p3K/1LYfUDo+PBrSoP1lYElNywC7YgpgeOs81ycr7ZKduxPenl8IJoJ7neHdFfRcXQgh/3gPrUna9XXBNgW1dhaCmbjgVD3OKmNif5WJR0uQKDHsQHycIo3gp2ugOiTq4fXzrU5Dpo=
  on:
    repo: FreeAllMedia/omnirouter
    branch: feature/watch
